server:
  port: 8081

spring:
  application:
    name: shipment
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/shipment
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true